### PR TITLE
Fix #5 - typeCoverage config to support atLeast

### LINKED ISSUE #5: Bug: typeCoverage config not working
**Describe the bug**

In the provided example, I am expecting the tool to fail since the expected actual coverage is `92%`, and my provided minimum is `99%`. This works when using the CLI option, but not when using the `typeCoverage` property in `package.json`.

Provided config:
```json
  "typeCoverage": {
    "atLeast": 99
  },
```

CLI output when using `typeCoverage` (wrong behavior):

image

CLI output when using `--threshold` option (expected behavior):
image

As a side note, noticed the `cache` option to generate `.ts-coverage` does not seem to work either, I suspect it may be related.

**To Reproduce**
See: https://codesandbox.io/s/crazy-sound-ujkcu

You can export the CodeSandbox as a zip and run locally after `yarn install`.

image

**Expected behaviour**
Using `typeCoverage` should have parity with `typescript-coverage-report` CLI options.

**Screenshots**
N/A

**Environment**
 - Tool version: 0.1.1
 - OS: MacOS 10.15.3
 - Node version: 12 LTS
 - Browser (if applicable): [e.g. chrome, safari]

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by tsaiDavid**
Please see this issue for details: #5 

A user's locally provided `typeCoverage` object would not be recognized, I took an approach very similar to what `type-coverage` itself [did](https://github.com/plantain-00/type-coverage/blob/5ad7db06e7c026f3c3a29bed6812dec01e40855b/packages/cli/src/index.ts#L67).

It differs in just a variety of ways:
- uses the sync versions of exists/readFile
- syntactic sugar of optional chaining 😇

Edit:
Was able to test this using `yarn link` and running `yarn build --watch` with a separate project that was using this package. Perhaps it might be helpful to add directions or suggestions on how to develop and contribute?

### CODE REVIEW

**Comment by alexcanessa** [comment]
@tsaiDavid to that note, I've created an issue (#7).

**Comment by alexcanessa** [comment]
So I just tested it using the previous way and it works. Are you sure that it wasn't working before?
(I also print the Object)

image

**Comment by tsaiDavid** [comment]
@alexcanessa - were you able to plug it into a separate project and run it?

**Comment by alexcanessa** [comment]
Oh, you're right.

In that case, is the path to the `package.json` that's wrong.

https://github.com/alexcanessa/typescript-coverage-report/blob/8682611ddea5776897cf41bb7cfa19832e40a6b0/src/bin/typescript-coverage-report.ts#L12

Has to become

```ts
} = require(path.join(process.cwd(), "/package.json"));
```

**Comment by tsaiDavid** [comment]
> @tsaiDavid - Oh, you're right.
> 
> In that case, is the path to the `package.json` that's wrong.
> 
> https://github.com/alexcanessa/typescript-coverage-report/blob/8682611ddea5776897cf41bb7cfa19832e40a6b0/src/bin/typescript-coverage-report.ts#L12
> 
> Has to become
> 
> ```ts
> } = require(path.join(process.cwd(), "/package.json"));
> ```

Wouldn't this cause issues with the `version` and `description`? As far as I can tell, you're importing the version and description to reveal to the end user of this CLI tool, but the `atLeast` comes from the user's project `package.json`

**Comment by alexcanessa** [comment]
> > @tsaiDavid - Oh, you're right.
> > In that case, is the path to the `package.json` that's wrong.
> > https://github.com/alexcanessa/typescript-coverage-report/blob/8682611ddea5776897cf41bb7cfa19832e40a6b0/src/bin/typescript-coverage-report.ts#L12
> > 
> > Has to become
> > ```ts
> > } = require(path.join(process.cwd(), "/package.json"));
> > ```
> 
> Wouldn't this cause issues with the `version` and `description`? As far as I can tell, you're importing the version and description to reveal to the end user of this CLI tool, but the `atLeast` comes from the user's project `package.json`

Yes sorry I meant to require two separate `package.json`.

**Comment by tsaiDavid** [comment]
@alexcanessa - gotcha, if we get this merged in then we can at least (no pun intended) support the `atLeast` from the user's `package.json`. I'm all ears!

**Comment by alexcanessa** [comment]
@tsaiDavid I slightly prefer to have just a second require as it sounds less convoluted, but I don't mind your implementation either.

If you resolve the conflict I can merge it (with or without the change).

**Comment by tsaiDavid** [comment]
@alexcanessa - sounds good, let me give your approach a try and fix the conflict!

**Comment by alexcanessa** [comment]
@tsaiDavid any news on this?

**Comment by alexcanessa** [comment]
Closing this as has been open for a while. Fixed elsewhere.

**Pull request closed without merging**
