### PR TITLE
chore(deps): updated typescript version

### PR DESCRIPTION
**Pull request by roikoren755**
Updated the version of typescript in the dev dependencies to 5.0.4, and added v5 of typescript as an accepted peer dependency

### CODE REVIEW

**Comment by delacroixe** [comment]
Good job, would be nice to have this PR approved.

**Comment by alexcanessa** [comment]
@all-contributors please add @roikoren755 for code.

**Comment by ribeaud** [comment]
Hallelujah! Now we just need someone making a new release...

**Comment by alexcanessa** [comment]
@ribeaud published. Sorry for the delay! Has been a few hectic weeks 😓

**Pull request merged**
