### PR TITLE
chore: move react to peer dependencies

### PR DESCRIPTION
**Pull request by jinphic**
typescript-coverage-report used as devDependencies,is best to move react-relate to peerDependencies, 
avoid changing the react version and influencing the build outputs，

### CODE REVIEW

**Comment by jinphic** [comment]
react is external most of the time, but ssr uses installed dependencies. it my change the build outputs

**Review by alexcanessa — APPROVED** [review]

**Comment by alexcanessa** [comment]
@all-contributors please add @jinphic for code

**Comment by MatthewTFarley** [comment]
This is an unfortunate change for non-React projects, which shouldn't have to manually install React just to satisfy the React peer dependency in typescript-coverage-report.

**Comment by alexcanessa** [comment]
@MatthewTFarley yes I figured the same thing. I also think I can avoid the usage of React altogether for this package.

**Pull request merged**
